[package]
name = "serve_dir"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"

tokio = { version = "1", features = ["full"] }

axum = { version = "0", features = ["tokio"] }
tower-http = { version = "0", features = ["full"] }
